// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpXuPlE3gSXnPoBUw6CFqlJOlztVSomxw',
    appId: '1:387695654258:web:ba5984706d6fcab3f059eb',
    messagingSenderId: '387695654258',
    projectId: 'chatapp-a8e4e',
    authDomain: 'chatapp-a8e4e.firebaseapp.com',
    storageBucket: 'chatapp-a8e4e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJkjVinlt_PEOcj3ePbl9NIV_7qAMxfu8',
    appId: '1:387695654258:android:3d00f0900bd675eef059eb',
    messagingSenderId: '387695654258',
    projectId: 'chatapp-a8e4e',
    storageBucket: 'chatapp-a8e4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgEle5emu1NNh3s0jnQlU15_1RhEz1DBA',
    appId: '1:387695654258:ios:1cf66de0eed8213cf059eb',
    messagingSenderId: '387695654258',
    projectId: 'chatapp-a8e4e',
    storageBucket: 'chatapp-a8e4e.firebasestorage.app',
    iosBundleId: 'kz.arken.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgEle5emu1NNh3s0jnQlU15_1RhEz1DBA',
    appId: '1:387695654258:ios:1cf66de0eed8213cf059eb',
    messagingSenderId: '387695654258',
    projectId: 'chatapp-a8e4e',
    storageBucket: 'chatapp-a8e4e.firebasestorage.app',
    iosBundleId: 'kz.arken.chatApp',
  );
}
